name: 01 Simple Release

on:
  workflow_dispatch:
    inputs:
      type-of-release-run:
        type: choice
        description: 'Do you run Release as?'
        required: true
        default: 'dry-run'
        options:
          - 'dry-run'
          - 'regular-release'

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run Semantic-Release (${{ github.event.inputs.type-of-release-run }} mode)
        run: |
          RELEASE_RUN_TYPE=${{ github.event.inputs.type-of-release-run }}
          echo "RELEASE_RUN_TYPE: $RELEASE_RUN_TYPE"
          if [ "$RELEASE_RUN_TYPE" == "regular-release" ]; then
            npx semantic-release
          else
            npx semantic-release --dry-run
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}